version: "3.9"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass123
      MYSQL_DATABASE: exampleDb
      MYSQL_USER: flaskapp
      MYSQL_PASSWORD: flaskapp
    command: ["--default-authentication-plugin=mysql_native_password"]
    healthcheck:
      test: ["CMD-SHELL","mysqladmin ping -uroot -prootpass123 --silent"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - mysql_data:/var/lib/mysql
    networks: [backend]

  workprofile:
    build:
      context: ..
      dockerfile: ./Dockerfile
    image: ayalagiyub/workprofile-advanced:dev
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      DB_USER: flaskapp
      DB_PASS: flaskapp
      DB_NAME: exampleDb
    ports:
      - "5000:5000"
    networks: [backend, frontend]

  nginx:
    image: nginx:alpine
    depends_on: [workprofile]
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks: [frontend]

networks:
  frontend: {}
  backend: {}

volumes:
  mysql_data: {}
